### PR TITLE
Customizable column ratios

### PR DESCRIPTION
**Pull request by ath3**
Ability to set custom column ratios in config file.

>columns=15,35,49
or
>columns=15:35:49

Default is 20:30:49
~~The sum of the numbers has to be 99~~
The sum of the numbers now doesn't have to be 99

### CODE REVIEW

**Comment by rabite0** [comment]
Looks good. While you're at it, could you maybe just remove the 0/99-based column ratios? That's probably wrong anyway.

**Comment by ath3** [comment]
Im not sure if i understand correctly:
You want to have the logic allowing any number for ratios - as done in the second commit, but doing the calculations in calculate_coordinates instead of doing it in config?

**Comment by rabite0** [comment]
Yeah, so that it's possible to use anywhere. Would be nice if it was part of HBox itself.

**Comment by rabite0** [comment]
If you don't have time or are having difficulties, I could also do it myself.

**Comment by ath3** [comment]
Sorry, i didnt have time, but I would like to work on it, if not sooner, then i will do it this weekend.

**Comment by ath3** [comment]
This change now also sets the minimal column size to 10, so if the ratio calculations would make it smaller than that, it will adjust the numbers.
The config parsing of invalid ratios should now be more robust, and if the input is not valid then the default ratios will be taken.

**Comment by rabite0** [comment]
Great, thank you!

**Pull request merged**
