### PR TITLE
Clarified the README a bit

### PR DESCRIPTION
**Pull request by gottaStartNow**
Worked on the README a bit, emphasized the nightly build aspect and clarified some of the wording.

### CODE REVIEW

**Comment by rabite0** [comment]
Hm.. Could you keep the changes to the actual clarifications? I like them, but you also changed a lot of the formatting and other stuff.

For example, "hunter" at the top  is too small now and written with a capital "H", which is wrong. You also added extra spaces in the features list. You also removed all the what's new entries.

Having a separate "Wanna Contribute?" headline with the IRC channel is a good idea though. That's fine, but the what's new stuff should stay so people who don't look at the github repo often miss any new features/changes.

Also the key bindings table it [totally broken](https://github.com/rabite0/hunter/blob/3cc068d2cbecf356f144abbc5054e196bdca77ac/README.md).

I suggest just keeping the textual changes you made and leaving everything else as it is. The contribute headline can stay though.

**Comment by gottaStartNow** [comment]
I will start with a fresh copy and just add the clarifications when I get home, no worries.

**Comment by rabite0** [comment]
I think github has it's own syntax for tables, but I'm not sure. I just followed an example I found.

**Comment by gottaStartNow** [comment]
I will double check all of that, I think that information should be moved from the README.MD and into a wiki or a Github pages. Then I can really organize it and be given a reason to spin up a a bunch of VM's to check the build instructions on each.

**Pull request closed without merging**
